version: '3'

services:
  loggar-app:
    image: openjdk:17
    build: .
    environment:
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_CHANNEL=${SPRING_REDIS_CHANNEL}
      - ELASTIC_CLOUD_ID=${ELASTIC_CLOUD_ID}
      - ELASTIC_CLOUD_API_KEY=${ELASTIC_CLOUD_API_KEY}
      - ELASTIC_CLOUD_URL=${ELASTIC_CLOUD_URL}
      - ELASTIC_INDEX_NAME=${ELASTIC_INDEX_NAME}
      - LOGGAR_SECURITY_CLIENTS=${LOGGAR_SECURITY_CLIENTS}
      - LOGGAR_SECURITY_KEY=${LOGGAR_SECURITY_KEY}
    volumes:
      - /tmp
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
