name: Deploy Loggar To DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Set Spring Boot Application Variables
        run: |
          echo "SPRING_VARIABLE=value" > .env
          # Add more environment variable definitions as needed

      - name: Build Spring Boot App
        run: mvn clean install -Dmaven.test.skip

      - name: Copy Files to Remote Machine
        run: scp -r Dockerfile redis docker-compose.yml target/*.jar root@167.71.130.32:/opt/loggar

      - name: SSH into Remote Machine and Deploy
        run: |
          ssh root@167.71.130.32 'cd /opt/loggar && docker-compose up -d --build'
